UPDATE lastposition t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE lastraw t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE laststatus t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE lastweather t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_message t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_telemetry t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_bulletin t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_frequency t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_message t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_object t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE last_telemetry t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE messages t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE position t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE cache_24hr t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE telemetry t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE telemetry_bits t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE telemetry_eqns t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE telemetry_parm t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE telemetry_unit t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE status t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
UPDATE weather t SET t.callsign_id = (SELECT c.id FROM callsign c WHERE c.source = t.source LIMIT 1) WHERE t.callsign_id=0 LIMIT 1000
